chore(project): config select changes
jwplayer/ott-web-app pull request #125
Opened 2022-07-22 13:50 UTC by AntonLantukh

## Description

- dev environment supported via a query 'env' value, now accessible from the dashboard
- change configs location to store them in one place with no copy/paste operations
- add prod configs to show on a production environment
- show test configs only for PRs and in e2e tests
- docs updated
- env variables stored in one place

### Steps completed:

According to our definition of done, I have completed the following steps:

- [ ] User stories met
- [ ] Storybook stories
- [ ] Unit tests added
- [ ] Linting passing
- [ ] Unit tests passing
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [ ] UX tested
- [ ] Browsers / platforms tested
- [ ] Rebased & ready to merge without conflicts
- [ ] Reviewed own code

2022-07-28 09:06 UTC, AntonLantukh commented
Suggestion: move 'internal' (dev api) configs to `configs/internal` folder. Use `dev` for real development mode.

2022-08-01 19:36 UTC, dbudzins requested changes
Sorry, I know there are a lot of comments, but in my defense, there are a lot of changes.

I propose we use the [modes mechanism](https://vitejs.dev/guide/env-and-mode.html#modes) of vite to specify the following different modes/environments with all of the settings defined in .env files:

1. `production` - Deployed to a real, customer site, shouldn't include any additional configs, locked down, config selector not shown
2. `demo` - the firebase demo. Connects to prod api and uses live configs from the api, not hard coded in the app. Perhaps we have a dictionary of ID's and descriptions defined in an env variable or a separate config file to populate the demo selector
3. `development` - the current dev setup for running locally (not called local because vite makes assumptions about .local files.) Connects to prod api by default and includes all configs (/dev and /test-e2e) for ease of testing. Config selector always shown.
4. `internal` - defaults to use the dev api (config files can all point to dev api data.) Not sure we need this tbh, but nice to distinguish internal from development.
5. `test` - used for unit/snapshot testing, does funny things with the css for snapshots to work. Doesn't need configs
6. `test-e2e` - only include the test configs, talk to the prod api, hide the selector so it's more representative of production

As suggested in the details above, I would only have test config files for the e2e tests that can also be used in dev.  Having too many example files is going to be confusing, hard to maintain, and give customers the impression not to use the nice dashboard system we just built. Connecting the demo to the dashboard is also going to make it easier for product people to maintain it and less likely there's conflict between test data and demo data.

Other than that, I would like to see all of the demo / selector code grouped together and isolated from the rest of the application as much as possible so it doesn't complicate the real business logic.

2022-08-01 19:36 UTC, budzworthy commented on types/env.d.ts
> +  readonly APP_INCLUDE_CONFIGS: 'dev' | 'test' | 'prod';
We probably don't need this included in the type definition, since it's only a build time param

2022-08-01 19:36 UTC, budzworthy commented on .env.test
> +APP_CONFIG_ALLOWED_SOURCES=0
Why the `0` here?

2022-08-01 19:36 UTC, budzworthy commented on vite.config.ts
> +    mode: process.env.APP_MODE || mode,
```suggestion
```

2022-08-01 19:36 UTC, budzworthy commented on configs/test/default--config.json
> +{
Does this have any functional differences from `blender--config.json`?  If not, let's drop the blender one and just keep this.

2022-08-01 19:36 UTC, budzworthy commented on package.json
> +    "start:e2e-test": "APP_MODE=test APP_INCLUDE_CONFIGS=test vite",
Instead of making more start package scripts, I suggest we create a .env file for each mode/environment and let the .env files capture all of the variables.

2022-08-01 19:36 UTC, budzworthy commented on .github/workflows/codeceptjs.yml
> +        run: yarn start:e2e-test &
```suggestion
        run: yarn start --mode test-e2e &
```

2022-08-01 19:36 UTC, budzworthy commented on .github/workflows/firebase-live.yml
> +        run: yarn && APP_UNSAFE_ALLOW_DYNAMIC_CONFIG=1 APP_INCLUDE_CONFIGS=prod yarn build
```suggestion
        run: yarn && yarn build --mode demo
```

2022-08-01 19:36 UTC, budzworthy commented on .github/workflows/firebase-preview.yml
> +        run: yarn && APP_UNSAFE_ALLOW_DYNAMIC_CONFIG=1 APP_INCLUDE_CONFIGS=test yarn build
```suggestion
        run: yarn && yarn build --mode demo
```

2022-08-01 19:36 UTC, budzworthy commented on docs/configuration.md
> +(!) Configs have `${NAME}--config.json` format, where words are separated by `-` sign. We also add `siteName` to the beginning of each config. You can also notice that every folder has its default co
You can omit the discussion about naming, since it's only really used for dev and demo with the config selector. We shouldn't be encouraging customers to try to use this.

2022-08-01 19:36 UTC, budzworthy commented on docs/configuration.md
> +
The description of the default behavior is a bit confusing / misleading. The APP_CONFIG_DEFAULT_SOURCE property should be the one and only determiner of a fallback.

2022-08-01 19:36 UTC, budzworthy commented on docs/e2e.md
> +4. Run `yarn start:e2e-test`
```suggestion
4. Run `yarn start --mode test-e2e`
```

2022-08-01 19:36 UTC, budzworthy commented on src/containers/Layout/Layout.tsx
> +      <UserMenu showPaymentsItem={accessModel !== 'AVOD'} onClick={loginButtonClickHandler} />
What does this onClick handler do (why was it added)?

2022-08-01 19:36 UTC, budzworthy commented on src/containers/Layout/Layout.tsx
> +    ({ blurImage, searchQuery, searchActive, userMenuOpen, showDebugTools }) => ({
I would try to keep the behavior of this pop up out of the main application, so that when it's disabled it can totally disappear and it doesn't complicate anything, since it's 99% mostly used for our own dev and demo purposes.

2022-08-01 19:36 UTC, budzworthy commented on src/env/index.ts
> +import { getQueryParam } from '#src/utils/history';
You can probably put this in `utils/env` instead of creating a whole subdirectory for `env`

2022-08-01 19:36 UTC, budzworthy commented on src/env/index.ts
> +export const INCLUDE_CONFIGS = getQueryParam('env') === 'dev' ? 'dev' : import.meta.env.APP_INCLUDE_CONFIGS;
Will this work? Aren't the configs included / excluded during build time?

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> -  return storage.getItem(configFileStorageKey)?.toLowerCase();
It's safest to keep the lowercasing here in case the stored value is not lowercase somehow

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> +  if (Number(UNSAFE_ALLOW_DYNAMIC_CONFIG)) {
This doesn't match the .env files, either add a `0` there or allow falsey here

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> -  if (INCLUDE_TEST_CONFIGS && source.startsWith('test--')) {
How will this check for allowed demo/test configs? Or I guess allow_unsafe_dynamic has to be true to use any of the demo/test configs?

2022-08-01 19:36 UTC, budzworthy commented on src/stores/UIStore.ts
> +  showDebugTools: boolean;
I would keep this out of the store so the dev component doesn't pollute the business logic of the main app

2022-08-01 19:36 UTC, budzworthy commented on src/utils/history.ts
> +  return params[value];
```suggestion
  const urlSearchParams = new URLSearchParams(window.location.search);

  return urlSearchParams.get(value);
```

2022-08-01 19:36 UTC, budzworthy commented on src/env/index.ts
> +export const API_HOST = getQueryParam('env') !== 'dev' ? import.meta.env.APP_API_BASE_URL : 'https://content-portal.jwplatform.com';
I recommend we do this query param check in the same place as `configOverride` so we can do the same thing to remove it from the url and probably use storage to maintain it between postbacks

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> +    return `/configs/${INCLUDE_CONFIGS}/${source}.json`;
Aren't the files included without the `prod`, `test`, etc. directories? Does this work as intended?

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> +  if (['prod', 'test', 'dev'].includes(INCLUDE_CONFIGS) && source.includes('--config')) {
What if we use a convention that won't overlap with any legit local/remote file names, like `local:<config>`

2022-08-01 19:36 UTC, budzworthy commented on src/env/index.ts
> +export const IS_DEV_BUILD = import.meta.env.MODE === 'development';
I think we can get rid of `IS_DEV_BUILD` and just use `IS_DEV_OR_TEST_BUILD` everywhere, otherwise it can get confusing to tell the difference between these 3 constants

2022-08-01 19:36 UTC, budzworthy commented on src/components/DevTools/DevTools.tsx
> +const getSystemConfigName = (siteName: string | undefined, configName: string | undefined) =>
It might be nice to expand the drop down component to accept values and labels so that you don't have to convert names back and forth.  Also, this would break if names don't follow the exact naming convention, which we don't have to be so rigid about.

2022-08-01 19:36 UTC, budzworthy commented on src/App.tsx
> +    logDev('Error while loading the config file:', error);
It would be nice to add a second param for the config location to the loading and error handlers to include in the log messages.

2022-08-01 19:36 UTC, budzworthy commented on src/components/DevTools/DevTools.tsx
> +  return siteName ? `${siteName} ${name}` : name;
Why do we add site name to the configs? It would make sense to show the site name defined in each config, but that would require loading all of them which is probably overkill.

2022-08-01 19:36 UTC, budzworthy commented on src/components/DevTools/DevTools.tsx
> +      return import.meta.glob(`../../../configs/test/*.json`);
Does it work to add an alias for the configs directory (i.e. `#config`) in vite.config.ts to avoid all the dots?

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> -    const configQuery = url.searchParams.get(configFileQueryKey)?.toLowerCase();
Also nice to keep  the lowercase here so that it's easier to manually enter something

2022-08-01 19:36 UTC, budzworthy commented on src/utils/configOverride.ts
> +    if (INCLUDE_CONFIGS !== 'dev') {
Why `!== dev`?  Shouldn't we always show it in dev?

2022-08-01 19:36 UTC, dbudzins commented on test-e2e/tests/account_test.ts
> +  I.useConfig('subscription--config');
If you're renaming all of the files, might as well make them as succinct as possible by dropping the `--config` along with the `test--`

2022-08-01 19:36 UTC, dbudzins commented on src/components/DevTools/DevTools.tsx
> +import { useMemo, useState } from 'react';
It probably makes sense to combine this file with the logic in overrideConfig, since they overlap almost entirely in function and purpose

2022-08-04 07:15 UTC, AntonLantukh commented
Thanks Danny. I will have a look a bit later when having free time during our spotlight project.

2022-08-04 07:32 UTC, ChristiaanScheermeijer commented on src/components/Sidebar/Sidebar.module.scss
> +  }
Does this still work well for keyboard tab navigation? It should not be possible to reach the menu items using the tab (shift+tab) key when the sidebar is not open.

2022-12-01 16:52 UTC, closed without merging